### ISSUE TITLE
调用URule的内置方法报空指针错误

### ISSUE THREAD

**Issue by zhaolong1990ok** [youseries/urule#10]
有一种情况， 比如  if( null !=  a && a > 2) 像这种如果a是引用类型， 是个对象的话， 没有非空的判断， 在规则执行的时候会抛空指针异常，实际希望的结果应该是如果只配置了a > 2 没做非空判断，当前的条件分支应该直接为false了。

比如调用里面的内置方法， DateAction里的一个方法， 参数是一个Date， 但是传入是NULL， 直接抛异常了， 执行不下去了。 （具体请看下面的例子）
![image](https://user-images.githubusercontent.com/3919124/33365819-62346cc4-d524-11e7-8d1b-6df026dcaf1c.png)

这里，如果受理时间遇到空值，直接抛出NullPointException异常了，而在配置规则处由于规则条件并不是有序的， 所以就算增加一个 【受理时间不为空的条件】也可能会存在这种问题。
![image](https://user-images.githubusercontent.com/3919124/33366136-503951d2-d525-11e7-9577-b0db16764e02.png)

**Comment by youseries** [comment]
已添加保护，请更新最新的2.1.2-SNAPSHOT测试，谢谢。
