### ISSUE TITLE
版本：2.1.6  为什么取消向导式规则中条件左侧添加方法或函数功能

### ISSUE THREAD

**Issue by lhch102** [youseries/urule#102]
## 版本：2.1.6  为什么取消向导式规则中条件左侧添加方法或函数功能
*  #### 相关截图：
![image](https://user-images.githubusercontent.com/21078340/42872528-bfc5deae-8aaf-11e8-8dbe-11da6315fee7.png)

**Comment by hlizard** [comment]
我现在也是困惑条件左右两边为什么不可以互换，这是出于什么样的考虑增加的限制，严重反人类！

**Comment by youseries** [comment]
取消原因是开源版在算法上对这种设计支持存在问题；不过可以使用PRO版本，PRO版完全支持！
