### ISSUE TITLE
同一个函数，不同参数获取的值却一致

### ISSUE THREAD

**Issue by Askerlve** [youseries/urule#104]
*  #### 当前使用的URule的具体版本号：

2.0.5-SNAPSHOT

- rule配置

```
if 
	字符串.获取长度(Api函数.获取指标v2(目标源,指标名,订单编号)) > 5
then
	日志函数.记录INFO日志("success!")
else
	日志函数.记录ERROR日志("error!")
end
```

- 当规则集中有多个这样的规则时，获取的值一直是一个，通过debug发现往EvaluationContext里面放缓存值的时候，生成的leftid一直是同一个。

![image](https://user-images.githubusercontent.com/14157567/43623257-e917f192-9712-11e8-940c-6720d64e5fd5.png)

- 问题代码，com.bstek.urule.model.rule.MethodValue.getId()

![image](https://user-images.githubusercontent.com/14157567/43623382-929819c2-9713-11e8-8657-f8aef524bc81.png)

- 做出尝试修改，问题解决

![image](https://user-images.githubusercontent.com/14157567/43623451-d82f9b68-9713-11e8-8256-b3c1b36f1fe8.png)

- 导致原因
&emsp;&emsp;同一个函数即使参数不同，但生成的id相同，导致不同参数的函数执行命中了缓存。

**Comment by youseries** [comment]
最新2.0.6-SNAPSHOT已修改，谢谢。
