### ISSUE TITLE
批量仿真测试 -> 上传excel后点击dialog左侧的第一个变量 -> 关掉dialog重新上传新excel，显示的数据为上一版excel的数据

### ISSUE THREAD

**Issue by guolanrui** [youseries/urule#105]
## 批量仿真测试 -> 上传excel后点击dialog左侧的第一个变量 -> 关掉dialog重新上传新excel，显示的数据为上一版excel的数据

*  #### 当前使用的URule的具体版本号：2.1.7-snapshot

*  #### 遇到的问题详细描述：
1.知识包-> 批量仿真测试 -> 下载excel模板
2.填写两份不一样的数据  demo1.xlsx     demo2.xlsx
3.上传excel   demo1.xlsx，然后点击一下左侧第一个变量，关掉弹窗
4.上传excel   demo2.xlsx，弹窗中展示的数据为demo1.xlsx中的数据，再次点击左侧变量后显示才是demo2.xlsx中的数据

*  #### 原因及解决方法：
原因是由于open dialog 时，没有把slavedata初始化；
解决方法是，在open时，将slavedata 初始化为 null，  或者在close时将slavedata置为null；

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
开源版BUG，请使用PRO版。
