### ISSUE TITLE
urule集成springmvc

### ISSUE THREAD

**Issue by crazy-gulang** [youseries/urule#109]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：

urule-console 2.1.6

*  #### 遇到的问题详细描述：

urule集成到springmvc项目中，数据库连接不上，按照文档上写的配置文件

*  #### 涉及到的异常信息（完整异常信息）：
无

*  #### 相关截图：
这是在urule的配置文件写的
![urule-](https://user-images.githubusercontent.com/42635799/44511091-fbaf6700-a6e8-11e8-9e57-f913c8f77ccc.png)
这是项目的jpa文件配置
![qq 20180823152820](https://user-images.githubusercontent.com/42635799/44511153-31545000-a6e9-11e8-8d58-951f1d50ab22.png)

这是通过spring的ContextLoaderListener加载的，在另一个springmvc项目中是通过DispatcherServlet加载的，但是配置文件这么写也不对？
问下怎么配置urule的配置文件？还有urule的配置文件都有哪些属性，怎么配置？

**Comment by youseries** [comment]
在springmvc项目中也要通过ContextLoaderListener加载，不能用DispatcherServlet加载。
