### ISSUE TITLE
tomcat加载urule2项目问题

### ISSUE THREAD

**Issue by crazy-gulang** [youseries/urule#110]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
urule-console 2.1.6

*  #### 遇到的问题详细描述：
1、我把项目加载到tomcat里边后，项目的访问路径就变成/urule了，不是项目名了
2、tomcat下加载的项目后边括号里便变成urule了

怎么将路径变回去？（除了修改tomcat的server.xml文件）
将项目后边括号里不是urule了？

*  #### 涉及到的异常信息（完整异常信息）：
无

*  #### 相关截图：
1、
![qq 20180903105359](https://user-images.githubusercontent.com/42635799/44965366-b51eff80-af67-11e8-971a-9fa93feae5b4.jpg)
2、
![qq 20180903105408](https://user-images.githubusercontent.com/42635799/44965368-bbad7700-af67-11e8-8075-aeb66ea1e1d8.png)

**Comment by youseries** [comment]
百度去。
