### ISSUE TITLE
交叉决策表topRow条件获取bug

### ISSUE THREAD

**Issue by lvyunxue** [youseries/urule#115]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
2.1.0 pro版

*  #### 遇到的问题详细描述：
1.交叉决策表如下配置，红框中的条件是永远不会执行的，不够其他条件满足与否。
![image](https://user-images.githubusercontent.com/20853050/51163875-27203180-18d6-11e9-83b0-d672535f8227.png)

2.原因在于该条件中的是没有编译进Rule对象中的Criteions中。问题出现的原因是在CrosstabRulesBuilder.findTopRowParentRange()方法中对targetRange的查找不准确。
![image](https://user-images.githubusercontent.com/20853050/51164021-a0b81f80-18d6-11e9-8dce-f3a9a944f18b.png)

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

*  #### 解决办法：
1.修改CrosstabRulesBuilder.findTopRowParentRange()方法，加上红色框中代码
![image](https://user-images.githubusercontent.com/20853050/51164624-897a3180-18d8-11e9-9b0c-d68339a542d8.png)

**Comment by youseries** [comment]
2.1.1版中已修复
