### ISSUE TITLE
评分卡行列赋值问题导致最终结果与期望不符

### ISSUE THREAD

**Issue by Askerlve** [youseries/urule#117]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号
   2.0.5-SNAPSHOT

*  #### 问题描述

* `定义评分卡规则如图`
![image](https://user-images.githubusercontent.com/14157567/51222773-2a6cf900-197a-11e9-857d-51fc4dca377d.png)

* `输入`
`age`:52;`自有-年龄`:26

* `输出`
![image](https://user-images.githubusercontent.com/14157567/51222891-8d5e9000-197a-11e9-8835-c1c5370d66b5.png)

* `期望`
得分为1的行应该为`1`,求和结果应该为`7`，实际为`6`

* `原因`
ScorecardResourceBuilder在构建ScoreRule的ScoringAction时，传入的参数不对。
![image](https://user-images.githubusercontent.com/14157567/51223093-6eacc900-197b-11e9-86a3-3a7d0b7a773e.png)
尝试做处改变：
![image](https://user-images.githubusercontent.com/14157567/51223118-8ab06a80-197b-11e9-8cbb-44a8cac4907f.png)
问题解决：
![image](https://user-images.githubusercontent.com/14157567/51223270-2cd05280-197c-11e9-810f-b0ffdd2d00c5.png)

* 看了下最新版本的代码，应该也有这个问题哦～

**Comment by youseries** [comment]
BUG.已修复。
