### ISSUE TITLE
URULE部署的问题

### ISSUE THREAD

**Issue by zhoukobe** [youseries/urule#12]
1 URULE独立部署时，客户端能否做的较量些，也就是在client端，不去集成urule-core，比如，client端可通过restful或webservice等通讯方式，通过json将数据发送到server端，server端对json解析后再映射到变量库内。
2 server端处理后的响应结果，通过json返回给client端，json内可包含命中的规则及参数库内规则涉及的结果参数。

**Comment by youseries** [comment]
不能。
