### ISSUE TITLE
URule 是 JSR94 的实现吗？

### ISSUE THREAD

**Issue by Rey70N** [youseries/urule#120]
URule 是 JSR94 的实现吗？

**Comment by lvyunxue** [comment]
Urule 底层使用的 jackrabbit 做为内容仓库进行存储的，jackrabbit 实现协议JSR-170

**Comment by Rey70N** [comment]
> Urule 底层使用的 jackrabbit 做为内容仓库进行存储的，jackrabbit 实现协议JSR-170

规则引擎本身呢？执行规则的核心

**Comment by lvyunxue** [comment]
规则引擎本身实现的Rete算法。关于rete算法原理，我认为这篇文章写得很好：https://www.ibm.com/developerworks/cn/opensource/os-drools/index.html

**Comment by youseries** [comment]
JSR94 只是一套api规范。
早期版本的urule实现了JSR94 的api，后来发现不好用，所以后续版本中将JSR94 实现删除了。
