### ISSUE TITLE
表达式右值为负数时，计算结果不正确

### ISSUE THREAD

**Issue by jannal** [youseries/urule#126]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：

*  #### 遇到的问题详细描述：

例如变量a和变量b，a-b或者1000-b。当变量b是负数时，获得的结果不正确。不是相加，而是减
比如a=2000 b=-1000 结果是a-b=1000 或者
2000-b = 1000
感觉ValueCompute 有bug，Number也与其他类型一样	expr.append("\""+obj+"\"");而不是使用
	expr.append(obj.toString()); 修改成这样不知道对不对。
	private void addToExpr(StringBuffer expr,Object obj){
		expr.append(" ");
		if(obj instanceof ArithmeticType){
			expr.append(obj.toString());			
		}else if(obj instanceof Number){
			expr.append(obj.toString());
		}else{
			expr.append("\""+obj+"\"");
		}
		expr.append(" ");
	}
	

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
试试pro版

**Comment by shuang669539827** [comment]
开源版这么多坑吗

**Comment by youseries** [comment]
是的。
