### ISSUE TITLE
获取KnowledgeService实例时，NullPointerException

### ISSUE THREAD

**Issue by NotFoundPoint** [youseries/urule#127]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
2.1.6

*  #### 遇到的问题详细描述：
 KnowledgeService service=(KnowledgeService) Utils.getApplicationContext().getBean(KnowledgeService.BEAN_ID);
获取实例时空指针异常

*  #### 涉及到的异常信息（完整异常信息）：
Exception in thread "main" java.lang.NullPointerException

*  #### 相关截图：

**Comment by youseries** [comment]
没有把urule加入到spring上下文环境，所以报错，安装请按照文档 http://www.bstek.com/resources/doc/2an-zhuang-yu-pei-zhi.html 操作。

**Comment by NotFoundPoint** [comment]
已经解决了 谢谢


------------------ 原始邮件 ------------------
发件人: "高杰"<notifications@github.com>;
发送时间: 2019年7月9日(星期二) 下午2:20
收件人: "youseries/urule"<urule@noreply.github.com>;
抄送: "魂↙斷__柒仴"<lll584131420@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youseries/urule] 获取KnowledgeService实例时，NullPointerException (#127)




没有把urule加入到spring上下文环境，所以报错，安装请按照文档 http://www.bstek.com/resources/doc/2an-zhuang-yu-pei-zhi.html 操作。
