### ISSUE TITLE
server端支持分布式部署吗？

### ISSUE THREAD

**Issue by ZBNLP** [youseries/urule#129]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
2.1.7

*  #### 遇到的问题详细描述：
server端支持分布式部署吗？

*  #### 涉及到的异常信息（完整异常信息）：
无

*  #### 相关截图：

**Comment by youseries** [comment]
支持，具体见：http://www.bstek.com/resources/doc/22fu-wu-bao-lu-yu-diao-yong.html
