### ISSUE TITLE
你好，资料库的账户如何获取？

### ISSUE THREAD

**Issue by landerTrim** [youseries/urule#132]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：

2.1.7

*  #### 遇到的问题详细描述：

查找资料的过程中发现资料库需要账户，请问开源的账户怎么获取

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/37889751/60781217-0d202700-a174-11e9-9bfc-b28412329d33.png)

**Comment by youseries** [comment]
那是老版文档库，目前已关闭，最新版文档地址：http://www.bstek.com/resources/doc/
