### ISSUE TITLE
资源文件与规则文件复制问题

### ISSUE THREAD

**Issue by landerTrim** [youseries/urule#133]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
  开源 2.1.3

*  #### 遇到的问题详细描述：
右击资源文件或规则文件，有个复制文件的功能，但点击后毫无反应，官网的在线体验项目也没有文件复制功能

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/37889751/61095653-e79e6080-a486-11e9-97ba-e8901f9baa4f.png)

**Comment by youseries** [comment]
可以在文件夹上粘贴，不能直接粘贴到某个分类下。

**Comment by youseries** [comment]
最新的2.1.8-SNAPSHOT已支持将文件粘贴到某个分类下。
