### ISSUE TITLE
脚本式规则使用循环规则，报空指针异常

### ISSUE THREAD

**Issue by lvyunxue** [youseries/urule#134]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
      urule-console-pro ：2.1.3
*  #### 遇到的问题详细描述：
   概述：在脚本式规则文件中，配置循环规则，循环规则的循环体没有被解析出来，导致测试时报：java.lang.NullPointerException
 1. 循环规则配置文件如下：
![image](https://user-images.githubusercontent.com/20853050/62193538-88a77980-b3aa-11e9-9d43-1de705099935.png)
 2.点击快速测试时：
![image](https://user-images.githubusercontent.com/20853050/62193576-9b21b300-b3aa-11e9-8286-e43b796364e7.png)

*  #### 涉及到的异常信息（完整异常信息）：
 ![image](https://user-images.githubusercontent.com/20853050/62194140-d2dd2a80-b3ab-11e9-8c74-9e7fe6f6672c.png)
异常原因为：List<LoopRuleUnit> units =null;根本原因为DSL解析脚本的循环规则时，循环体没有被解析出来。
 ![image](https://user-images.githubusercontent.com/20853050/62194164-e4becd80-b3ab-11e9-8fd5-7a19d14fa0aa.png)

*  #### 相关截图：

**Comment by youseries** [comment]
最新的2.1.8-SNAPSHOT中已修复，且同时支持多循环单元，谢谢。
