### ISSUE TITLE
urule-console-js缺少文件

### ISSUE THREAD

**Issue by byejude** [youseries/urule#137]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：

2.1.7
*  #### 遇到的问题详细描述：

ERROR in multi (webpack)-dev-server/client?http://localhost:8080 ./src/client/index.jsx

src下缺少client目录

*  #### 涉及到的异常信息（完整异常信息）：
ERROR in multi (webpack)-dev-server/client?http://localhost:8080 ./src/client/index.jsx

*  #### 相关截图：

**Comment by youseries** [comment]
源码需要自己搞定。

**Comment by youseries** [comment]
源码不提供支持。
