### ISSUE TITLE
【bug】修改常量，规则流需要删除再添加？？

### ISSUE THREAD

**Issue by huaxuehuaxue** [youseries/urule#139]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
2.1.7

*  #### 遇到的问题详细描述：
修改常量的值，规则流不能生效，需要删除相应的分支、规则集，然后重新添加。

*  #### 涉及到的异常信息（完整异常信息）：

无
*  #### 相关截图：
无

**Comment by youseries** [comment]
常量的修改要通过“重构”功能实现（在URule Pro版中有“重构”功能），不能直接修改后保存，否则对于已经使用了当前常量的文件不会生效。
