### ISSUE TITLE
session使用完之后是否需要释放资源？

### ISSUE THREAD

**Issue by onfdtz** [youseries/urule#143]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：

2.1.3

*  #### 遇到的问题详细描述：

您好，我想请问下session每次使用完，是否需要销毁或者释放操作呢？
因为我的应用场景会不断新建session，如果没有释放操作，一段时间后，是否会占满资源呢？
谢谢～

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
不需要释放，引擎会自动回收，放心。

**Comment by onfdtz** [comment]
嗯好，谢谢～










在 2019-09-04 13:49:23，"高杰" <notifications@github.com> 写道：


不需要释放，引擎会自动回收，放心。
