### ISSUE TITLE
LHS的RETE网络构建问题

### ISSUE THREAD

**Issue by MarkGao11520** [youseries/urule#149]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
2.2.1

*  #### 遇到的问题详细描述：
LHS的rete构建是从ObjectTypeActivity作为DAG的起点，TerminalTypeActivity作为DAG的终点，但是这样执行的话，会有很多可以短路的条件还是会被执行，比如OrNode本来是只要有一个节点满足，则其他的都不用计算了，但是这里是都会计算，请问这样设计是有什么考虑吗？

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/29473873/67470332-2647d780-f680-11e9-9727-2c8d7d33a2d7.png)

**Comment by youseries** [comment]
开源版算法就是这样，可以试试pro版。
