### ISSUE TITLE
多个fact只能匹配一个

### ISSUE THREAD

**Issue by MarkGao11520** [youseries/urule#150]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：

2.2.1

*  #### 遇到的问题详细描述：

开源版，KnowledgeSession insert多个相同类型的fact后，第一个fact evaluationRete后，没有重置 CriteriaActivity，导致后面的fact都无法进行匹配 

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/29473873/67653993-ebe38080-f986-11e9-8fb7-ac38470c684a.png)
![image](https://user-images.githubusercontent.com/29473873/67653998-f140cb00-f986-11e9-888d-eff65ae0239f.png)

**Comment by youseries** [comment]
开源版就是这么设计的，可以试试 pro，pro版支持同类型对象多实例。
