### ISSUE TITLE
决策流规则事件不执行

### ISSUE THREAD

**Issue by shaoyn** [youseries/urule#18]
由于RuleNodeParser类，解析方法里面没有解析xml中event-bean节点，导致规则流事件不执行，后来在解析方法里面加入node.setEventBean(element.attributeValue("event-bean")); 问题解决

**Comment by youseries** [comment]
你可以提个PR上来，我参考下。

**Comment by youseries** [comment]
最新的2.1.4-SNAPSHOT中已处理，谢谢。
