### ISSUE TITLE
规则集向导编写时，facts属性直接参与运算时，页面存在空格

### ISSUE THREAD

**Issue by houjunFang** [youseries/urule#19]
![bug](https://user-images.githubusercontent.com/15853333/34034524-e17a2d60-e1b9-11e7-94c0-5ef1f177ba50.png)
1、规则集向导编写时，facts属性直接参与运算时，页面存在空格；
2、ElCalculator.calculate() 方法未作字符去空格处理；203行 result=first.divide(second) 进行BigDecimal除不尽时会报java.lang.ArithmeticException: Non-terminating decimal expansion; no exact representable decimal result 异常。

**Comment by youseries** [comment]
问题1，就是这样设计的，为修改留出空间。
问题2，BUG，已修复，更新最新的2.1.4-SNAPSHOT测试。
