### ISSUE TITLE
决策表的条件判断问题

### ISSUE THREAD

**Issue by lbeffor** [youseries/urule#22]
您好，我遇到这样一个问题，在决策表设定条件时，条件列设置为变量的一个属性，这个属性是List集合，元素是字符串。在表格中设置条件，想判断指定的字符串是否包含在这个集合中。如果能加一下包含的条件判断就好了。

**Comment by youseries** [comment]
添加"包含"和"不包含"两个新的比较操作符，用于实现左值为字符串以及集合类型值是否包含右值字符串及集合类型值判断，请更新最新版SNAPSHOT测试，谢谢。
