### ISSUE TITLE
请教一下，执行规则流时客户端的输入类该怎么定义，是每个都insert一遍吗？还是怎样

### ISSUE THREAD

**Issue by BinWoo** [youseries/urule#25]
在执行规则的时候，我知道应该fire的是那个变量类。但是，如果是规则流，可能每个规则流的变量类都不一样，我该怎么做？

**Comment by youseries** [comment]
在执行startProcess前把相关规则流以及其绑定的规则包中需要用到的对象全部insert进去，系统会自动处理。

**Comment by BinWoo** [comment]
全部多次insert，是吧？

**Comment by youseries** [comment]
用到的对象全部insert进去
