### ISSUE TITLE
urule更新规则后需要重启服务器客户端才能获取到最新的规则信息

### ISSUE THREAD

**Issue by kiana168** [youseries/urule#26]

**Comment by kiana168** [comment]
urule.knowledgeUpdateCycle=0，确定每次执行都有**Load knowledgepackage from remote...**，但是更新规则之后，只有在重启服务端，客户端才能请求到最新的规则

**Comment by youseries** [comment]
更新规则之后，需要到知识包那里，找到当前修改过的规则所在的知识包，然后点击工具栏上“ 发布当前知识包”即可。

**Comment by kiana168** [comment]
谢谢
