### ISSUE TITLE
urule采用数据库存储没有成功

### ISSUE THREAD

**Issue by forezp** [youseries/urule#28]
![image](https://user-images.githubusercontent.com/11371924/34349630-2fa8f43a-ea4d-11e7-9e34-318796198e20.png)
![image](https://user-images.githubusercontent.com/11371924/34349632-36f875a8-ea4d-11e7-88bd-1049e3ef2c15.png)

图1是配置，图2采用直连mysql的方式

这是springboot的 application.properties:
#urule.repository.dir=/Users/forezp/Downloads/com
server.port=8081

完全按照文档来的一直成功不来 
版本2.1.4快照版

**Comment by passionke** [comment]
在springboot中 不需要配置xml了吧

直接配置

![image](https://user-images.githubusercontent.com/168310/34350251-f5a23b58-ea50-11e7-8047-99a62a884cee.png)

**Comment by passionke** [comment]
保证dataSource是一个 springboot的规范 ds即可
我用的是druid

![image](https://user-images.githubusercontent.com/168310/34350285-1c182c3e-ea51-11e7-8ca0-c8ec257f6013.png)

**Comment by silverYi** [comment]
请问你们这个springboot 规则存储在数据库这里集成搞定了吗？


这个地方的mysql.xml你们怎么解决的

**Comment by silverYi** [comment]
@Component
public class PropertiesConfiguration extends URulePropertyPlaceholderConfigurer implements InitializingBean{
	@Override
	public void afterPropertiesSet() throws Exception {
		Properties props=new Properties();
		props.setProperty("urule.repository.xml", "mysql.xml");
		setProperties(props);
	}

}
这个地方mysql.xml是怎么处理呢，毕竟这是springboot，没有xml配置了

**Comment by woftan** [comment]
数据库配置文件要在哪个配置文件里加载吗？怎么配置上没有反应呢
`urule.repository.xml=
urule.decisionTree.style=new
urule.welcomePage=
urule.console.title=URule Console
urule.repository.datasourcename=dataSource
urule.repository.databasetype=mysql`

`<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
	xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
		http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-3.0.xsd">
	<bean id="dataSource" class="org.apache.commons.dbcp.BasicDataSource">
	    <property name="url"
	        value="jdbc:mysql://localhost:3306/edas_rule?useUnicode=true&amp;characterEncoding=UTF-8" />
	    <property name="driverClassName" value="com.mysql.jdbc.Driver" />
	    <property name="username" value="root" />
	    <property name="password" value="root" />
	    <property name="minIdle" value="5" />
	    <property name="maxActive" value="10" />
	    <property name="maxWait" value="1000" />
	    <property name="removeAbandonedTimeout" value="60" />
	    <property name="removeAbandoned" value="true" />
	    <property name="logAbandoned" value="true" />
	</bean>
</beans>`
