### ISSUE TITLE
第一个规则中参数赋值后，后面的规则参数和数值比较有问题。

### ISSUE THREAD

**Issue by jianjian0814** [youseries/urule#31]
第一个规则中参数赋值后，后面的规则参数和数值比较有问题，但是规则输出那可以拿到值。

帮忙给看看，谢谢。
![1](https://user-images.githubusercontent.com/24446722/34369469-e30937a2-eaf6-11e7-9154-b7a646af719c.png)

**Comment by youseries** [comment]
你这需求涉及到工作区对象更新，具体请先看工作区对象更新对应视频，看完之后或许你就知道如何做！

**Comment by jianjian0814** [comment]
视频在哪下载啊

**Comment by youseries** [comment]
看wiki文档，里面有视频文档下载链接。

**Comment by jianjian0814** [comment]
![image](https://user-images.githubusercontent.com/24446722/34402254-70309d3e-ebdb-11e7-8565-a386c4306508.png)
![image](https://user-images.githubusercontent.com/24446722/34402275-882b70e4-ebdb-11e7-9643-c4fcf0bb99c5.png)


按照视频配置，加上但是那么和否则都执行了

**Comment by youseries** [comment]
否则执行，是因为你第一次条件不满足，所以执行否则，在你更新工作区中参数后，规则再次尝试匹配，条件满足，所以就执行那么，没有什么问题。
规则执行与你想象中略有不同，你还需要好好理解下！
