### ISSUE TITLE
删除或修改规则引用的al.xml、vl.xml、pl.xml、cl.xml后，规则报错，再保存后规则里面就什么也没有了。

### ISSUE THREAD

**Issue by jianjian0814** [youseries/urule#32]
删除或修改规则引用的al.xml、vl.xml、pl.xml、cl.xml后，规则报错，再保存后规则里面就什么也没有了。

**Comment by youseries** [comment]
这是对的，删除后导致文件无法解析，打开的规则就是个空的，再保存就只会保存这个空的，所以出现你遇到的问题。
