### ISSUE TITLE
关于mysql数据库有些表乱码问题

### ISSUE THREAD

**Issue by zx353589545** [youseries/urule#34]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：

2.02

*  #### 遇到的问题详细描述：

转成mysql后，下面这一堆表都不知道啥意思，一堆乱码，有大神简单说明一下吗，各种懵逼，就看懂了个存xml的表

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

![table](https://user-images.githubusercontent.com/29905715/34403753-2eb7c9ae-ebe5-11e7-9038-da2fe3d381a7.png)

**Comment by youseries** [comment]
首先你的urule版本太低，建议升级到最新版，具体版本可以到：search.maven.org上查询。
对于你这里，其实不是乱码，是将java对象序列化存储。所以是正常的。
