### ISSUE TITLE
评分卡的得分计算方式为自定义时，指定的Bean中无法获取行信息，行数为0

### ISSUE THREAD

**Issue by liamjung** [youseries/urule#39]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
版本号：2.1.1

*  #### 遇到的问题详细描述：
评分卡的得分计算方式为自定义时，指定的Bean中无法获取行信息，行数为0
下面截图的例子中应该为2

*  #### 涉及到的异常信息（完整异常信息）：
无异常信息

*  #### 相关截图：
![1](https://user-images.githubusercontent.com/16040295/34509037-8e46eb8a-f080-11e7-945a-bcbaeb1bcaeb.png)
![2](https://user-images.githubusercontent.com/16040295/34509060-c56d3d12-f080-11e7-94f6-8fe5ec450f67.png)

**Comment by youseries** [comment]
这里的rowItems只会返回条件满足的项目，也就是说如果你的评分卡里没有满足的分值，那么这里就是空的，可以看看你的是不是这样。

**Comment by liamjung** [comment]
@youseries 问题已解决，跟你说的一样，评分卡里没有满足的分值
