### ISSUE TITLE
客户端调用规则，匹配的规则数量返回值总是为0

### ISSUE THREAD

**Issue by zhaolong1990ok** [youseries/urule#4]
在仿真测试或者代码调用规则，成功执行完then的部分，肯定是有匹配到规则的，但是返回的结果总是为0.

例如建立的规则如下：
![image](https://user-images.githubusercontent.com/3919124/31989545-30ff2544-b9a5-11e7-845a-e981448a5720.png)

代码中通过API调用结果如下：
![image](https://user-images.githubusercontent.com/3919124/31989576-4bf67a96-b9a5-11e7-876c-e35c6c5834ec.png)

**Comment by youseries** [comment]
无论是本地调用，还是远程客户端调用，返回执行规则数量都是对的，没出现你说的问题！

**Comment by youseries** [comment]
已修复
