### ISSUE TITLE
在urule-springboot 项目中怎么配置连接mysql， 把规则保存于mysql 中

### ISSUE THREAD

**Issue by galen-guo** [youseries/urule#40]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：

2.1.3

*  #### 遇到的问题详细描述：

在urule-springboot 项目中怎么配置连接mysql， 把规则保存于mysql 中

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
看文档：http://wiki.bsdn.org/pages/viewpage.action?pageId=75071583

**Comment by stevenshane** [comment]
> 

404 Not Found
nginx/1.6.2

**Comment by stevenshane** [comment]
> 看文档：http://wiki.bsdn.org/pages/viewpage.action?pageId=75071583

404 Not Found
nginx/1.6.2

**Comment by gcnote** [comment]
您好，您发的邮件我已收到，谢谢！！！

**Comment by stevenshane** [comment]
> 

可以分享一下吗？lanseshangbing.w@163.com
