### ISSUE TITLE
urule2 嵌入iFrame问题

### ISSUE THREAD

**Issue by SherryDing** [youseries/urule#44]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：2.0.5

*  #### 遇到的问题详细描述：urule中http://localhost:[port]/[contextPath]/urule/frame页面嵌入我的iframe中,要改哪里

*  #### 涉及到的异常信息（完整异常信息）：
Refused to display 'http://..../urule/frame?_t=883362&_winid=w5154' in a frame because it set 'X-Frame-Options' to 'deny'.

*  #### 相关截图：

**Comment by youseries** [comment]
直接把urule的URL放在iframe的src属性里即可。

**Comment by SherryDing** [comment]
是放到src里面的，好像不行。




                                        


                                                                                                            丁雪丽
在2018年1月8日 10:18，高杰<notifications@github.com> 写道：

直接把urule的URL放在iframe的src属性里即可。

**Comment by youseries** [comment]
有什么错误吗？
