### ISSUE TITLE
代码中如何获取规则结果？

### ISSUE THREAD

**Issue by futengsheng** [youseries/urule#45]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：2.1.3

*  #### 遇到的问题详细描述：代码调用的时候执行session.fireRules()后，如何得到规则的结果呢？目前看文档只有在控制台中输出？是否有可以直接获取规则结果的方法呢？

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
规则执行过程实际上是对变量或参数赋值的过程，所以结果就是获取对相关变量及参数就可以看到规则因条件满足而触发的动作；不存在返回值之类，详情看视频。
