### ISSUE TITLE
决策流中规则无论是否满足都会继续流转到后续节点？

### ISSUE THREAD

**Issue by favesing** [youseries/urule#48]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
2.1.4

*  #### 遇到的问题详细描述：
在决策流中无论是否满足规则，都会继续流转。而规则仅仅是根据条件执行了相关的动作。
之前一直以为不满足规则会自动中断决策流，这个决策流该如何理解？

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
是的，规则流的作用只是对现有的各种规则进行编排，具体规则的执行不会影响规则流的执行。
