### ISSUE TITLE
URULE获取知识包ID

### ISSUE THREAD

**Issue by kiana168** [youseries/urule#50]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：

urule-console 2.1.4

*  #### 遇到的问题详细描述：

能不能从数据库获取知识包ID或者有相应方法能够得到项目下的知识包ID

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
不能，只能通过URule提供的API实现，比如你这里就可以通过RepositoryReader接口的loadProjectResourcePackages方法取到某个项目所有的知识包定义信息。
