### ISSUE TITLE
获取决策流ID和知识包下多个决策流，调用规则代码

### ISSUE THREAD

**Issue by kiana168** [youseries/urule#51]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：

urule-console2.1.4

*  #### 遇到的问题详细描述：
①当规则非常多的时候，把不同对象分为不同执行规则放在规则表里，然后再一个决策流中调用n多规则，是否效率非常的低，只有通过分规则分知识包调用提高效率的方法吗？（由于规则过多，我们采取的方法是获取知识包ID以及对应的决策流ID作为参数进行knowledgeService创建）
②如果一个知识包下除了有决策表决策树外还有多个决策流，那在服务端调用规则时session.startProcess(决策流ID);要如何配置

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
- 问题一，用规则流对大量规则进行编排，相比直接执行规则集效率肯定会有一些下降，但也不至于非常低。对于客户端调用规则来说，就是从远程获取知识包可能是比较费时的，所以需要我们按照教程（http://wiki.bsdn.org/pages/viewpage.action?pageId=75071588）配置好urule.knowledgeUpdateCycle参数，充分利用客户端中知识包的缓存功能，否则每次都从服务端获取知识包（默认就是这样）那性能肯定很差。

- 如果一个业务需要有多个规则流配合才能完成，那么可以用一个大的规则流将这些小的规则流串起来执行即可。具体做法就是这个大的规则流通过添加“知识包”节点来与一个包含规则流的知识包绑定，这样执行时引擎在执行到这个“知识包”节点时会自动执行里面的包含的规则流（如果里面有规则流的话，如果没有则执行fireRules()）
