### ISSUE TITLE
urule在规则调用中动态insert Fact

### ISSUE THREAD

**Issue by scudy** [youseries/urule#52]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：

2.1.4

*  #### 遇到的问题详细描述：

Urule现在还不能在规则调用中动态增加fact ，只能对外部传入的fact做处理。 
drools可以insert变量

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
不懂你意思。

**Comment by jinxiaoxin** [comment]
请问您的这个问题解决了吗？能否交流一下，，我也有同样的需求
