### ISSUE TITLE
osgi+内置jetty集成Ureport

### ISSUE THREAD

**Issue by JiangChen123** [youseries/urule#54]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：

2.2.3

*  #### 遇到的问题详细描述：
操作过程
>1、新建一个插件ureport
>2、将console改成ureport的fragement,将core与font改成普通插件
>3、添加相关依赖与配置(xml文件放在ureport的WEB-INF/resource)
>4、启动程序，能访问https://jiangchen/report,但是输入https://jiangchen/report/ureport
报500
>>猜测ureport的服务没启动
结果
WebApplicationContext获取到

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
请在ureport的issue里与ureport相关问题。
