### ISSUE TITLE
URule拼接变量，第一个变量如果为null后面的变量无论为任何值最后的赋值结果都为null

### ISSUE THREAD

**Issue by zhaozhenzzz** [youseries/urule#55]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
2.1.4

*  #### 遇到的问题详细描述：
URule拼接变量，第一个变量如果为null后面的变量无论为任何值最后的赋值结果都为null。如果是第二个变量为null则是正常的。

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
最新版SNAPSHOT中已修复。
