### ISSUE TITLE
采用urule客户端服务端模式，服务端规则不在客户端本地,规则中用到”更新参数“方法，session.startProcess()报错

### ISSUE THREAD

**Issue by jaloer123** [youseries/urule#60]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
urule2.1.3

*  #### 遇到的问题详细描述：
规则中使用了更新参数，采用urule客户端服务端模式，session.startProcess()后，若urule客户端调用远端规则，urule源码RemoteServiceImpl里的getKnowledge方法里边的解析规则json会报错，无法正常执行规则。
![image](https://user-images.githubusercontent.com/11372593/34939745-f1b764e6-fa27-11e7-8796-76983dcc22a8.png)

*  #### 涉及到的异常信息（完整异常信息）：
![image](https://user-images.githubusercontent.com/11372593/34939771-0210b7d4-fa28-11e7-901a-0ba6a1bf92d3.png)
![image](https://user-images.githubusercontent.com/11372593/34939828-30671880-fa28-11e7-826e-bea55a218558.png)
 
![image](https://user-images.githubusercontent.com/11372593/34940400-59857462-fa2a-11e7-81e3-8c71ff4d0328.png)

*  #### 相关截图：

**Comment by youseries** [comment]
试试最新版
