### ISSUE TITLE
采用客户端服务端模式，允许调试信息输出选是，但无效

### ISSUE THREAD

**Issue by jaloer123** [youseries/urule#61]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
2.1.3

*  #### 遇到的问题详细描述：
采用客户端服务端模式，允许调试信息输出选是，但不打印.
使用urule-console的非客户端服务端模式 可以打印。
（配置过了urule.debug=true urule.debugToFile=true 写了session.writeToFile()）

*  #### 涉及到的异常信息（完整异常信息）：
控制台不打允许印调试信息输出的日志，其余日志都正常打印

*  #### 相关截图：

**Comment by followyourheart0** [comment]
采用客户端服务端模式，允许调试信息输出选是，但无效  。同样是这个问题，希望可以得到回答

**Comment by followyourheart0** [comment]
环境：当前使用的是urule的2.1.4版本，采用客户端-服务端模式，独立部署服务端，业务系统直接调用API。
遇到问题如下：在服务端做仿真测试是没有问题的，并且是可以在控制台打出输出；但是在业务系统调用的时，客户端和服务端都不报错，业务系统的客户端就是没有返回信息输出的日志 ？
请问这样问题如何解决。谢谢。

**Comment by youseries** [comment]
是最新的2.1.4在客户端调用不输出日志吗?

**Comment by jaloer123** [comment]
我是2.1.3在客户端不输出 “允许调试信息输出”选是 的 日志。
1楼说的应该是2.1.4也不打印

**Comment by followyourheart0** [comment]
在使用urule，总结一些经验，和大家分享一下。
关于urule的client-server模式，客户端不打印“添加动作”的问题，经过调试有以下解决方案：
1. 升级到最新版本，并且是client和server保持一致版本
2.在添加"变量库"中的"类路径"要和代码中的实体包全限名一致

**Comment by jaloer123** [comment]
正常“添加动作”里的输出日志打印，只是规则属性里新功能“调试信息输出” 不打印

**Comment by followyourheart0** [comment]
楼上可以加微信，我在实践该产品，一起交流。我微信：followyourheart01 ，加时候备注一下。

**Comment by youseries** [comment]
你们多交流 :)
