### ISSUE TITLE
决策文件的版本控制问题

### ISSUE THREAD

**Issue by jpf199** [youseries/urule#65]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
    

*  #### 遇到的问题详细描述：
    决策文件保存为新版本后，然后打开新版本，进行修改，点击保存，保存到的root版本，而不是当前版本，请问设计如此吗？

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
不明白你意思。

**Comment by jpf199** [comment]
我在决策集下有一个规则文件，然后保存为新版本1.0，然后打开这个文件，在点击保存，保存的不是1.0版本的这个文件，而是原始root版本的文件，这是设计初衷吗？

**Comment by youseries** [comment]
版本保存就是这样，不可能对一个文件版本进行修改后保存，修改后保存只会产生新版本，不懂可以看看svn,git等。
