### ISSUE TITLE
客户端与服务端的知识包无法及时同步

### ISSUE THREAD

**Issue by followyourheart0** [youseries/urule#66]
问题一、采用client-server模式，server独立部署。当可视化客户端修改业务规则时，业务端调用还是历史记录，没有及时把服务端知识包同步客户端，除非重新启动tomcat服务。

关于官网文档的一段话“如果urule.knowledgeUpdateCycle为1，那么它会首先检查客户端本地缓存当中是否存在指定的知识包，如果存在，就取本地缓存中的，如果不存在，则到URule Server下请求指定的知识包”，这时如果在客户端可视化界面修改业务规则，客户端再请求server的知识包，这个知识包不是最新的。基于以上问题，翻看一下源码，源码底层是同步模式来做的。导致客户端-服务端知识包不能同步。
一实践分享，供参考。或者作者给出解答。

**Comment by jpf199** [comment]
需要在知识包页面上面，点击发布知识包，才会刷新缓存和客户端

**Comment by youseries** [comment]
文档里介绍的很清楚，如你所说需要服务端“点击发布知识包”才会重新编译当前包对应的规则文件，同时客户端如果是web项目，也可以采用推的方式，这样服务端与客户端就会实时同步，具体看文档介绍。
