### ISSUE TITLE
脚本式决策集关于比较符号的用法

### ISSUE THREAD

**Issue by zx353589545** [youseries/urule#68]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
2.0.2

*  #### 遇到的问题详细描述：
脚本式决策集

*  #### 涉及到的异常信息（完整异常信息）：
脚本式决策集一下关键字的用法是什么？
例如:
变量.属性>=18是可以的，
变量.属性 Startwith “18” 就不行,
能不能举个例子说明下用法

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/29905715/35673389-628f8746-077c-11e8-98dd-42ae61e2246c.png)

**Comment by youseries** [comment]
请看文档，另外也请更新至最新版，你的版本有些老。
