### ISSUE TITLE
优先级是否可以设为-1

### ISSUE THREAD

**Issue by kiana168** [youseries/urule#69]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：

urule-console-2.1.4

*  #### 遇到的问题详细描述：

urule文档写着决策集优先级默认为0，为了使修改的操作尽可能少，我把一个公共决策集优先级改为-1，-1应该是可以的吧？

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
不可以。
