### ISSUE TITLE
决策流回复节点执行问题

### ISSUE THREAD

**Issue by favesing** [youseries/urule#70]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
2.1.4-SNAPSHOT

*  #### 遇到的问题详细描述：
请问：urule决策流当中，如果执行到某一个节点依赖外部数据（还未准备好数据）中断后，能否下次重新从该节点恢复执行后面的流程，而不是从头来执行决策流

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
不能，如需比功能可以使用uflo
