### ISSUE TITLE
urule-console的iconfont库地址能给一个吗

### ISSUE THREAD

**Issue by favesing** [youseries/urule#72]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
2.1.14

*  #### 遇到的问题详细描述：
urule-console的iconfont库地址能给一个吗

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
给不了，抱歉！
