### ISSUE TITLE
urule-console-js这个模块，有具体的编译命令吗？比如webpack

### ISSUE THREAD

**Issue by lhjbusi** [youseries/urule#73]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：

*  #### 遇到的问题详细描述：
cnpm install
webpack
两个命令执行编译的，但是编译完决策表的页面无法打开报js错误

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
这里不支持源码，抱歉！
