### ISSUE TITLE
删除库文件（变量、常量文件等），在工程启动后日志显示仍然在加载这些已经被删除的文件

### ISSUE THREAD

**Issue by SimonKGit** [youseries/urule#74]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
urule-core2.1.5

*  #### 遇到的问题详细描述：
删除库文件（变量、常量文件等），在工程启动后日志显示仍然在加载，在控制台被删除的已经消失了。

*  #### 涉及到的异常信息（完整异常信息）：
删除无用的库文件后，在加载阶段仍然会加载，导致应用启动过程太长。历史数据无法彻底删除的问题希望能核实下，谢谢。

*  #### 相关截图：
![qq 20180305181152](https://user-images.githubusercontent.com/7557495/36969944-db717a3c-20a1-11e8-98b9-e26ffd8f0df1.jpg)
![qq 20180305181221](https://user-images.githubusercontent.com/7557495/36969945-dbb76024-20a1-11e8-84b7-399cdeb9f761.jpg)
![qq 20180305181657](https://user-images.githubusercontent.com/7557495/36969946-dbf649ec-20a1-11e8-9acf-09f40ea3743e.jpg)
![qq 20180305181921](https://user-images.githubusercontent.com/7557495/36969947-dc376288-20a1-11e8-8941-96869cd528f2.jpg)

**Comment by youseries** [comment]
没看懂你意思！

**Comment by SimonKGit** [comment]
@youseries  就是比如日志截图里的那个/快快快/省道.dt.xml是我已经删除了的文件，但是在工程启动的时候日志显示仍然在打印这些我已经删除的东西，之前测试的东西有点多后来全删掉了，现在这块儿有点拖慢工程启动速度。

**Comment by youseries** [comment]
这是由jackrabbit的机制导致，jackrabbit是一款带有版本控制功能的存储工具，所以它不会直正删除任何文件（否则某些时候你想恢复的时候就做不到了），这点可以类比svn，git等，所以文件即使删除还可以在控制台看到它。
