### ISSUE TITLE
知识包-仿真测试中使用“上传Excel测试数据”一直显示“导入Excel失败”

### ISSUE THREAD

**Issue by dragon0574** [youseries/urule#77]
### 当前使用的URule的具体版本号：
`urule-console2.1.4`

### 遇到的问题详细描述：
> 在做一个评分卡的小项目，单独通过直接填写数据“测试决策宝”可以输出正常结果。
现在有一批数据，大概200多条，故打算通过`下载Excel测试数据模板`==>本地向模板填写数据==>`上传Excel测试数据`来达到测试数据的目的
但是在执行`上传Excel测试数据`时，提示`导入Excel数据失败`。经分析是前端报错

### 分析过程：
* 请求：/hkrule/urule/packageeditor/importExcelTemplate
* 后端：在项目`urule-console`中找到类`com.bstek.urule.console.servlet.respackage.PackageServletHandler`的方法`importExcelTemplate`就是`上传Excel测试数据`功能所对应的后台代码，经debug跟踪，后台无报错或异常，Excel的数据读取正常，方法里的对象mapData所报保存的数据就是Excel里所录入的数据
* 前端：浏览器端查看对应请求的`respone`里存放的是读取到的Excel里的数据，是json形式的，经前端debug是在如下图红框处报错的

![sp20180308_154257](https://user-images.githubusercontent.com/26729969/37139068-7c4f4c44-22e7-11e8-990d-ae34da339871.jpg)
执行`console.log($(e.target).contents().text())`打印出`$(e.target).contents().text()`的内容，发现如下信息，前面是一个json字符串，后面红色标注部分请重点关注
![sp20180308_155450](https://user-images.githubusercontent.com/26729969/37139507-19e55f06-22e9-11e8-892a-c141d08d53e3.jpg)
明显是由于多出来的这些内容影响了`$.parseJSON()`的执行，然后报错，进而输出了`导入Excel失败`。
问题至此已经描述的比较清楚了，烦请大佬抽时间看下是什么问题引起的。

*  #### 涉及到的异常信息（完整异常信息）：
> 前端后端控制台无任何异常信息输出
![sp20180308_154450](https://user-images.githubusercontent.com/26729969/37139134-b40b91ec-22e7-11e8-9268-8693bf60ce02.jpg)

**Comment by dragon0574** [comment]
这个问题通过我自己的努力已经结局了，烦请大佬关注其他的issue。
解决方式：我是用chrome浏览器，装了一个插件VIP看电影，根据第二张截图多出来的信息，猜测到有可能是跟vip有关的东西造成的，尝试将VIP看电影这个插件关掉后，就可以正常上传了

**Comment by youseries** [comment]
这个插件叫什么名字，我装个试试。

**Comment by lhch102** [comment]
![image](https://user-images.githubusercontent.com/21078340/42872354-4ecbabca-8aaf-11e8-9e44-6966d151d257.png)

Tampermonkey

**Comment by CuriousRookie** [comment]
> ![image](https://user-images.githubusercontent.com/21078340/42872354-4ecbabca-8aaf-11e8-9e44-6966d151d257.png)
> 
> Tampermonkey

不止是Tampermonkey，Adblock Plus、沙拉查词。。。我Chrome装了这几个插件都会有这问题，关了就好了
