### ISSUE TITLE
可否开放BuiltInActionLibraryBuilder的buildMethod方法

### ISSUE THREAD

**Issue by wendal** [youseries/urule#78]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
2.1.4

*  #### 遇到的问题详细描述：
BuiltInActionLibraryBuilder的buildMethod是私有方法,无法直接调用
所以无法动态添加@ActionBean对象

*  #### 涉及到的异常信息（完整异常信息）：
无

*  #### 相关截图：
无

**Comment by Wizzercn** [comment]
围观

**Comment by youseries** [comment]
可以通过反射去调。

**Comment by wendal** [comment]
反射当然可以, 我就问问能不能开放

**Comment by youseries** [comment]
目前不考虑开放。
