### ISSUE TITLE
urule修改文件路径问题

### ISSUE THREAD

**Issue by favesing** [youseries/urule#79]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
2.1.14

*  #### 遇到的问题详细描述：
urule中修改文件路径或名称导致其他决策流引入的文件路径不同加载失败，必须手动的修改，这个问题如何完美的解决呢

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
可以使用URule的商用PRO版本，PRO版本中带有重构功能，开源版不提供重构功能。PRO版使用方法见：http://wiki.bsdn.org/pages/viewpage.action?pageId=75071533
