### ISSUE TITLE
为什么在一个评分卡里面只能选择一个变量库

### ISSUE THREAD

**Issue by jiepansoft** [youseries/urule#8]
为什么在一个评分卡里面只能选择一个变量库，这样设计的目的是啥

**Comment by youseries** [comment]
评分卡就是这样！

**Comment by jiepansoft** [comment]
好像昨天说错了，我的意思是一个变量库有多个类，但是在一个评分卡里面只能选择一个类，假如根据多个类的N个字段计算分值那就没法搞了

**Comment by youseries** [comment]
多个类可以用多个评分卡实现，通过优先级定义执行顺序，通过一个参数来存储评分卡的分值，这个分值在多张评分卡中共享即可。

**Comment by jiepansoft** [comment]
那咋把各个评分卡的值合计呢，试了试好像搞不定
