### ISSUE TITLE
URule2的导出导出、引用轨迹以及数据保存的疑惑？

### ISSUE THREAD

**Issue by zhuyoupeng** [youseries/urule#80]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：2.1.5-SNAPSHOT

*  #### 遇到的问题详细描述：
        第一：目前URule2的项目导出导出只支持整题导出，但我想要实现单独导出，例如：更改哪几个资源库和规则决策，我就分别导出更改的几个文件，然后分别导如(主要用于测试上生产的增量情况，不想每次上全量，有一定的风险)？
        第二：我想要实现在更改变量库时，能够看到哪些决策引用了这个变量对象，以便知道是否存在更改的风险？
        第三：保存方式现在都是以Nosql方式保存，我想要换成sql方式进行落地，是否能够实现？
        刚刚接触URule2一周的时间，因为想要实现上面的问题，始终没有找到头绪，希望管理或者各位大神们能够给些指导意见和建议，谢谢！

*  #### 涉及到的异常信息（完整异常信息）：暂无异常

*  #### 相关截图：无截图

**Comment by youseries** [comment]
第一：不支持
第二：开源版支持引用变量、参数或常量文件查看功能，在商用PRO版中除了支持引用查看（PRO版更多信息：http://www.bstek.com/products/urule），还支持重构，也就是更改变量、参数或常量名时，会对所有引用的文件进行同步修改。
第三：不支持。
