### ISSUE TITLE
nexus私服（http://nexus.bsdn.org ）当了 不能访问

### ISSUE THREAD

**Issue by liuzyhn** [youseries/urule#81]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
2.0.1

*  #### 遇到的问题详细描述：

私服宕机了 不能下载jar

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
urule包不在http://nexus.bsdn.org上，而在https://oss.sonatype.org/#welcome上，具体见安装配置文档。
