### ISSUE TITLE
新建任何知识包都无法发布出去！

### ISSUE THREAD

**Issue by zengyufei** [youseries/urule#85]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：

2.0.5 、2.1.2-5

*  #### 遇到的问题详细描述：

无法发布一个知识包

*  #### 涉及到的异常信息（完整异常信息）：

无异常

*  #### 相关截图：
![snipaste_2018-04-09_14-54-02](https://user-images.githubusercontent.com/13251679/38483614-28a8f76a-3c06-11e8-9262-6faa210d9658.png)

**Comment by youseries** [comment]
我本地是好的，这么多年还是第一次有人报这个问题，你应该检查你自己的环境或操作。

**Comment by zengyufei** [comment]
重装过系统，jdk 8， idea 2018.1 环境，下载 urule-springboot，启动后 chrome 访问 localhost:8080 新建知识包，依然 ！无论如何都发布知识包不出去。
换火狐游览器也是一样。
