### ISSUE TITLE
代码调用知识包执行规则没有执行指定得规则

### ISSUE THREAD

**Issue by kingorknight** [youseries/urule#86]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
2.1.3

*  #### 遇到的问题详细描述：
配置好了评分卡和知识包,在代码中执行知识包中规则,返回得结果永远是0 ,规则没有匹配执行
但在测试中可以得到

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/30260028/38622789-88d5f7e2-3dd6-11e8-8687-2ee71f55befd.png)
![image](https://user-images.githubusercontent.com/30260028/38622876-ca5bff7c-3dd6-11e8-966b-c62e12eccd12.png)
![image](https://user-images.githubusercontent.com/30260028/38622906-d9d8ed84-3dd6-11e8-8720-c37a4727e62d.png)
![image](https://user-images.githubusercontent.com/30260028/38622914-e36b75b0-3dd6-11e8-8d9f-dbdf25f63f2f.png)
![image](https://user-images.githubusercontent.com/30260028/38622944-f82054e4-3dd6-11e8-8c9c-2831bc5826ae.png)

**Comment by youseries** [comment]
刚测了下，是好的。
![a](https://user-images.githubusercontent.com/29193502/38655332-8c3e4608-3e46-11e8-95d0-35aaed8d9b76.png)
![b](https://user-images.githubusercontent.com/29193502/38655345-9a2ac570-3e46-11e8-9e44-3aa36c79f2bf.png)
