### ISSUE TITLE
决策树左边值选择方法，如果条件有三个，那么方法也会被调用三次

### ISSUE THREAD

**Issue by dnhxm** [youseries/urule#88]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
2.1.6-SNAPSHOT(在修复上述问题的commit之后)

*  #### 遇到的问题详细描述：
比如我使用决策树时，第一个变量选择方法 字符串-获取字符串长度-选择变量X
然后加三个条件 小于3 ->Action 小于5->Action 大于5->Action
那么在真正执行决策树时，获取字符串长度(变量X) 这个动作会被执行三次

*  #### 涉及到的异常信息（完整异常信息）：
无

*  #### 相关截图：
无

**Comment by dnhxm** [comment]
比如我使用决策树时，第一个变量选择方法 字符串-获取字符串长度-选择变量X 
然后加三个条件 小于3 ->Action  小于5->Action 大于5->Action
那么在真正执行决策树时，获取字符串长度(变量X)  这个动作会被执行三次

**Comment by dnhxm** [comment]
?

**Comment by youseries** [comment]
决策树在编译会分拆下面的条件，所以分执行三次。

**Comment by dnhxm** [comment]
那如果我自定义的方法是比较复杂的计算，而且条件又多的话，那执行N次性能就会很差，而且RETE算法的Alpha节点是有存储已执行节点的值的功能，这样实现不太好吧？
