### ISSUE TITLE
2.1.1-SNAPSHOT 这个版本创建决策流  关联知识包报错 

### ISSUE THREAD

**Issue by sunrain520** [youseries/urule#9]
![image](https://user-images.githubusercontent.com/8476392/33242225-62acee02-d30c-11e7-98eb-209ab9470966.png)

![image](https://user-images.githubusercontent.com/8476392/33242242-9cbe9564-d30c-11e7-85c3-29eca7a4c97f.png)

这时候是有一个知识包的

**Comment by sunrain520** [comment]
创建决策流 关联知识包 2.1 版本的使用正常   ， 并且还发现一个问题，2.1.1-SNAPSHOT导出的中文包 无法导入 2.1版本 这个可能是跟之前 无法导出中文包有关。
使用中  还会时不时发现莫名其妙的 问题 ， 比如 我新建一个 中文名称评分卡  发布知识包了 再删掉了 再建一样的名字的评分卡   会报错 已存在  刷新确实没有   是不是这个文件关联有问题呢？

**Comment by youseries** [comment]
你这异常不完整，请附上完整异常信息。
另外其它信息这里无法重现！
