### ISSUE TITLE
urule-pro-2.0.3 仿真测试无法输入List类型变量值为[1,2,3,5,6]

### ISSUE THREAD

**Issue by favesing** [youseries/urule#90]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：

urule-pro-2.0.3

*  #### 遇到的问题详细描述：

仿真测试里，无法输入List变量值(格式类似：list[1,2,3,4,5]),  而只能是 {rows:xxx, type:xxx}这样的格式

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![6d2f15ea-9d95-4c5a-9e72-945c313b2bff](https://user-images.githubusercontent.com/555043/39162947-be98e47e-47aa-11e8-85a1-0307c2b8933d.png)

**Comment by youseries** [comment]
这个功能会改进，谢谢。

**Comment by youseries** [comment]
最新的2.0.3-SNAPSHOT中已完善此功能，谢谢。
