### ISSUE TITLE
决策流里的脚本中的加号无法正常保存

### ISSUE THREAD

**Issue by hlizard** [youseries/urule#93]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
2.1.7-SNAPSHOT

*  #### 遇到的问题详细描述：
决策流里的脚本中的加号无法正常保存（保存成功，但是重新打开后加号消失）

*  #### 涉及到的异常信息（完整异常信息）：
无

*  #### 相关截图：

**Comment by youseries** [comment]
你怎么写的？截图上来说明下。

**Comment by hlizard** [comment]
![image](https://user-images.githubusercontent.com/6994037/40213227-f37a1a5c-5a86-11e8-9994-88a578550661.png)

就这种脚本里的加号，保存时没提示，再打开加号就没了

**Comment by youseries** [comment]
数据提交时转码导致，最新版SNAPSHOT中已修复，请下载测试，谢谢。
