### ISSUE TITLE
如何获取触发的每个规则执行的参数结果

### ISSUE THREAD

**Issue by dhxy5117** [youseries/urule#95]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：

2.1.6

*  #### 遇到的问题详细描述：

现在通过session.firerules()能获取到定义的参数的最终结果，如何查看所有被触发的规则的结果信息呢？

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
规则执行没有返回值的概念，规则执行一般都是对变量或参数赋值，通过修改变量或参数值实现规则计算的目的。

**Comment by dhxy5117** [comment]
@youseries 好的，我通过自定义动作赋值给变量实现了
