### ISSUE TITLE
互斥组 多条件判断错误

### ISSUE THREAD

**Issue by altercyx** [youseries/urule#96]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
2.1.6

*  #### 遇到的问题详细描述：
互斥组里面的 每个规则中包含多个条件(循环规则

) 则如果第一个规则的第一个条件匹配成功 则就算匹配了
例如 rule1 a=b and b=c 如果 a=b 成立 则 不论b=c 成立与否 互斥组就退出了

*  #### 涉及到的异常信息（完整异常信息）：
无异常信息

*  #### 相关截图：

![b1](https://user-images.githubusercontent.com/4946413/41142726-4870d32c-6b29-11e8-8439-4e149cab3fe8.PNG)
![b2](https://user-images.githubusercontent.com/4946413/41142750-66332504-6b29-11e8-8e35-25d0e89b6aba.PNG)
![r1](https://user-images.githubusercontent.com/4946413/41142755-6b222790-6b29-11e8-8e7b-bd26c6851916.PNG)
![r2](https://user-images.githubusercontent.com/4946413/41142758-6fbce1be-6b29-11e8-8c5f-072819dc18ce.PNG)
![c1](https://user-images.githubusercontent.com/4946413/41142791-8de2b7b8-6b29-11e8-8f04-d714b7fa0c9f.PNG)

**Comment by altercyx** [comment]
同样存在问题，对所有的 循环规则的 互斥 无效，
今天发现pro的代码编辑器有问题，开原版没有

**Comment by youseries** [comment]
添加Else导致，可以试试最新的PRO版2.0.5-SNAPSHOT，里面做了处理。

**Comment by lhch102** [comment]
请教个问题，规则集中定义内置动作库后，客户端调用服务端规则后，客户端报错：
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'rCheckOrderAction' is defined
是怎么回事？

**Comment by altercyx** [comment]
你没仔细看文档，需要先声明为bean
