### ISSUE TITLE
关于List变量的赋值问题

### ISSUE THREAD

**Issue by chzhm** [youseries/urule#97]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：2.1.6-SNAPSHOT

*  #### 遇到的问题详细描述：
实验了一下两种配置方法：list的个数都没有增加，请问这种类型应该如何配置
1. 在动作部分，给匹配列表赋值，list个数为0
2. 在动作部分，直接调用List的向list添加对象，list的个数依然为0

*  #### 涉及到的异常信息（完整异常信息）：
☢☢☢控制台输出：0
☢☢☢控制台输出：0

*  #### 相关截图：

![20180620190746](https://user-images.githubusercontent.com/40427551/41655154-80cbaae6-74be-11e8-8427-0137420d9c15.jpg)

**Comment by youseries** [comment]
动作“向List中添加对象”是没有返回值的，所有你的第二个变量赋值动作有问题，从而导致后面的结果和你想的不一样。
