### ISSUE TITLE
2.1.7版的权限设置页面，选择项目阅读权限后其他选项没有展示

### ISSUE THREAD

**Issue by guolanrui** [youseries/urule#99]
## 2.1.7版的权限设置页面，选择项目阅读权限后其他选项没有展示。

*  #### 当前使用的URule的具体版本号： 2.1.7-snapshot

Google Chrome 已是最新版本
版本 67.0.3396.99（正式版本） （64 位）

*  #### 遇到的问题详细描述：资源权限配置-用户-项目-是否允许查看当前项目-是，选完是后，其他配置项不显示。
debug后发现是radio上的onChange事件没有触发造成的，改成onClick后可以正常使用

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
最新的2.1.7-SNAPSHOT版本中已修复。
